config/routes.rb
Rails.application.routes.draw do

  root "receptionists#index"
  resources :guests #this will replace all the paths in routes file automatically (paths to 7 operations)
  resources :receptionists, only: [:index, :create]
  resources :sessions, only: [:create]
  get "log_out" => "sessions#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest.rb
class Guest < ApplicationRecord
	belongs_to :receptionist

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/;
	VALID_MOBILE_FIELD = /\d[1-9][0-9]\)*\z/;

	validates :name, :email_id, presence:true
	validates :email_id, format: {with: VALID_EMAIL_REGEX, uniqueness: {:case_sensitive => false}, message: "Eg - example@xyz.com"}
	validates :mobile_no, :numericality => {:only_integer => true}, :length => { :minimum => 10, :maximum => 10 }, format: {with: VALID_MOBILE_FIELD}
	validates_length_of :mobile_no, :minimum => 10, :maximum => 10, :allow_blank => false
	validates :name, format: {with: /\A[a-zA-Z]+(?: [a-zA-Z]+)?\z/, uniqueness: {:case_sensitive => false}, message: "only allows alphabets"}#/\A[a-zA-Z]+\z/

end

app/models/receptionist.rb
class Receptionist < ApplicationRecord
  has_secure_password
  has_many :guests

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/;

  validates :name, :email_id, presence:true
  #validates :my_email_attribute, email: true
  validates :email_id, format: {with: VALID_EMAIL_REGEX, uniqueness: {:case_sensitive => false}, message: "Eg - example@xyz.com"}
  #validates :mobile_no, :numericality => {:only_integer => true}
  validates :name, format: {with: /\A[a-zA-Z]+(?: [a-zA-Z]+)?\z/, uniqueness: {:case_sensitive => false}, message: "only allows alphabets"}#/\A[a-zA-Z]+\z/
  validates :email_id, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_cache_buster
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_receptionist
    Receptionist.find(session[:receptionist_id]) if session[:receptionist_id]
  end

  def require_login
    unless session[:receptionist_id]
      flash[:errors]=['You must Login first']
      redirect_to root_path
    end
  end

  def current_user
    if session[:receptionist_id]
      Receptionist.find_by_id(session[:receptionist_id])
    else
      return nil
    end
  end

  def set_cache_buster
    response.headers['Cache-Control'] = 'no-cache, no-store, max-age=0, must-revalidate'
    response.headers['Pragma'] = 'no-cache'
    response.headers['Expires'] = expires_now()
  end

end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :require_login
  before_action :set_guest, only: [:show, :edit, :update, :destroy]

  # GET /guests
  # GET /guests.json
  def index
    @name = params[:receptionist_name]
    if current_user.is_admin
      @guests = Guest.all
    elsif current_user.email_id
      @guests = Receptionist.find_by_email_id(current_user.email_id).guests
    end
  end


  # GET /guests/1
  # GET /guests/1.json
  def show
  end

  # GET /guests/new
  def new
    @guest = Guest.new
  end

  # GET /guests/1/edit
  def edit
  end

  # POST /guests
  # POST /guests.json
  def create
    if current_receptionist
      @guest = current_receptionist.guests.new(guest_params)

      if @guest.in_time <= @guest.out_time
        respond_to do |format|
          if @guest.save
           format.html { redirect_to @guest, notice: 'Guest was successfully created.' }
            format.json { render :show, status: :created, location: @guest }
          else
           format.html { render :new }
           format.json { render json: @guest.errors, status: :unprocessable_entity }
          end
          end
      else
        flash[:error] = 'Out-time should be greater than In-time'
      end
    end
  end


  # PATCH/PUT /guests/1
  # PATCH/PUT /guests/1.json
  def update
    respond_to do |format|
      if @guest.update(guest_params)
        format.html { redirect_to @guest, notice: 'Guest was successfully updated.' }
        format.json { render :show, status: :ok, location: @guest }
      else
        format.html { render :edit }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1
  # DELETE /guests/1.json
  def destroy
    @guest.destroy
    respond_to do |format|
      format.html { redirect_to guests_url, notice: 'Guest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_guest
    @guest = Guest.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def guest_params
    params.require(:guest).permit(:name, :email_id, :mobile_no, :in_time, :out_time, :receptionist_id, :is_admin)
  end
end

app/controllers/receptionists_controller.rb
class ReceptionistsController < ApplicationController

  def index
      if current_user
        redirect_to guests_path
      else
        @receptionist = Receptionist.new
      end
  end

  def create
    receptionist = Receptionist.new(receptionist_params)
    if receptionist.save
      flash[:notice] = "Receptionist successfully created"

      if current_user == nil && receptionist.id
        session[:receptionist_id] = receptionist.id
        redirect_to receptionists_path
      elsif current_user.email_id == "admin@coreuser.com" && receptionist.id
        redirect_to guests_path
      end

    else
      flash[:errors] = receptionist.errors.full_messages
      redirect_to receptionists_path
    end
  end

  def show
    @receptionist = Receptionist.find(params[:id])
    @guests = @receptionist.guests
  end

  private
  def receptionist_params
    params.require(:receptionist).permit(:name, :email_id, :password, :password_confirmation, :is_admin)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    receptionist = Receptionist.find_by(email_id: params[:email_id])
    if receptionist && receptionist.authenticate(params[:password])
      session[:receptionist_id] = receptionist.id
      redirect_to guests_path(receptionist_id: receptionist, receptionist_email_id: receptionist.email_id, receptionist_name: receptionist.name, is_admin: receptionist.is_admin)
    else
      flash[:errors] = ['Invalid Combination!']
      redirect_to receptionists_path
    end
  end

  def destroy
        reset_session
        redirect_to :root, notice: 'Logged out'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/receptionists_helper.rb
module ReceptionistsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/guests/_form.html.erb
<%= form_with(model: guest, local: true) do |form| %>
  <% if guest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(guest.errors.count, "error") %> prohibited this guest from being saved:</h2>

      <ul>
      <% guest.errors.full_messages.each do |message| %>
            <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %><br>
    <%= form.text_field :name, id: :guest_name, placeholder: "Enter a name", title: "Enter only alphabets" %>
  </div>

  <div class="field">
    <%= form.label :email_id %><br>
    <%= form.text_field :email_id, id: :guest_email_id, placeholder: "Enter email id", title: "Enter email in this format: ex- character@character.domain" %>
  </div>

  <div class="field">
    <%= form.label :mobile_no %><br>
    <%= form.text_field :mobile_no, id: :guest_mobile_no, placeholder: "Enter phone number", title: "Enter only 10 digit" %>
  </div>

  <div class="field">
    <%= form.label :in_time %><br>
    <%= form.datetime_select :in_time, id: :guest_in_time %>
  </div>

  <div class="field">
    <%= form.label :out_time %><br>
    <%= form.datetime_select :out_time, id: :guest_out_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/guests/edit.html.erb
<style>
  h1 {
    background-color: orange;
    padding: 5%;
    font-family: 'Noto Sans CJK SC Bold';
  }
</style>

<h1>Atithi</h1>

<h2>Editing Guest</h2>

<%= render 'form', guest: @guest %>

<button><%= link_to 'Show', @guest %></button> |
<button><%= link_to 'Back', guests_path %></button>

app/views/guests/index.html.erb
<style>
  h1 {
    background-color: orange;
    padding: 5%;
    font-family: "Noto Sans CJK SC Bold";
  }
  .btn-color{
    color: red;
    text-decoration-color: red;
  }
  .name {
    cursor: pointer;
  }
  table, th, td {
    border: 2px solid black;
  }
  table {
    border-collapse: collapse;
    width: 100%;
  }
  th {
    text-align: center;
    height: 50px;
  }
  td {
    text-align: center;
  }
  .btn-color {
  }
  #myInput {
    background-position: 10px 12px; /* Position the search icon */
    background-repeat: no-repeat; /* Do not repeat the icon image */
    width: 20%; /* Full-width */
    font-size: 16px; /* Increase font-size */
    padding: 12px 20px 12px 40px; /* Add some padding */
    border: 1px solid #ddd; /* Add a grey border */
    margin-bottom: 12px; /* Add some space below the input */
  }
</style>

<script rel = "application.js"></script>

<h1>Atithi</h1>

<p id = "notice"><%= notice %></p>

<% if current_user.email_id != "admin@coreuser.com" %>
    <h4>Receptionist</h4>
    <h4>User:<%= current_user.name%></h4>
<%else%>
    <h4>Admin</h4>
    <h4>User:<%= current_user.name%></h4>
<% end %>

<h2>Guests List</h2>

<input type = "text" id = "myInput" onkeyup = "myFunction()" placeholder = "Search for names..">

<table id = "myTable">
  <thead>
  <tr>
    <th onclick = "sortTable(0)", class = "name">Name</th>
    <th>Email</th>
    <th>Mobile no</th>
    <th>In time</th>
    <th>Out time</th>
    <th>Receptionist</th>
    <th colspan = "3">Actions</th>
  </tr>
  </thead>



  <tbody>
  <% if @guests.ids.first == nil %>
      <tr><td colspan="9", style="font-size: medium">No data to show</td></tr>
  <%else%>
      <% @guests.each do |guest| %>
          <tr>
            <td><%= guest.name %></td>
            <td><%= guest.email_id %></td>
            <td><%= guest.mobile_no %></td>
            <td><%= guest.in_time %></td>
            <td><%= guest.out_time %></td>
            <td><%= guest.receptionist.name %></td>
            <td><%= link_to 'Show', guest %></td>
            <td><%= link_to 'Edit', edit_guest_path(guest) %></td>
            <td><%= link_to 'Destroy', guest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      <% end %>
  <% end %>
  </tbody>
</table>

<br>

<% if current_user.id == 41 %>
    <button class = "btn-color"><%= link_to 'New Guest', new_guest_path %></button>
    <button><%= link_to 'Log out', "/log_out" %></button>

<% else %>
    <button><%= link_to 'New Guest', new_guest_path %></button>
    <button><%= link_to 'Log out', "/log_out" %></button></br>

<% end %>

app/views/guests/new.html.erb
<h1>Atithi</h1>
<style>
  h1 {
    background-color: orange;
    padding: 5%;
    font-family: "Noto Sans CJK SC Bold";
  }
</style>

<% if flash[:error] %>
    <div class = "error"><%= flash[:error] %></div>
<% end %>

<h2>New Guest</h2>

<%= render 'form', guest: @guest %>

<button><%= link_to 'Back', guests_path(current_user.id, current_user.email_id, current_user.name) %></button>

app/views/guests/show.html.erb
<h1>Atithi</h1>
<style>
  h1 {
    background-color: orange;
    padding: 5%;
    font-family: "Noto Sans CJK SC Bold";
  }
</style>

<p id = "notice"><%= notice %></p>

<table>
  <strong>Name:</strong>
  <%= @guest.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @guest.email_id %>
  </p>

  <p>
    <strong>Mobile no:</strong>
    <%= @guest.mobile_no %>
  </p>

  <p>
    <strong>In time:</strong>
    <%= @guest.in_time %>
  </p>

  <p>
    <strong>Out time:</strong>
    <%= @guest.out_time %>
  </p>
</table>
<button><%= link_to 'Edit', edit_guest_path(@guest) %> </button> |
<button><%= link_to 'Show table', guests_path(current_user.id, current_user.email_id, current_user.name) %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/receptionists/index.html.erb
<h1>Atithi</h1>

<style>
  h1 {
    background-color: orange;
    padding: 5%;
    font-family: "Noto Sans CJK SC Bold";
  }
  h2 {
    background-color: #CCCCCC;
    padding:3%;
    font-family: FreeSans;
  }
</style>

<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>

<% if flash[:errors] %>
    <div class="row">
      <% flash[:errors].each do |e| %>
          <p class="text-danger"><%= e %></p>
      <% end %>
    </div>
<% end %>

<div class="row">

  <div id="registration" class="col-md-6">
    <h2> Register </h2>
    <%= form_for @receptionist do |f| %>

        <div class="form-group">
          <%= f.label :name %><br>
          <%= f.text_field :name, placeholder: "Enter a name", title: "enter only alphabets" %>
        </div>

        <div class="form-group">
          <%= f.label :email_id %><br>
          <%= f.email_field :email_id, placeholder: "Enter email id", title: "Enter email in this format: ex- character@character.domian" %>
        </div>

        <div class="form-group">
          <%= f.label :password %><br>
          <%= f.password_field :password, placeholder: "Enter password", title: "Enter new password" %>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation %><br>
          <%= f.password_field :password_confirmation, placeholder: "Enter same password", title: "Re-enter new password" %>
        </div>
        <br>

        <%= f.submit %>

    <% end %>
  </div>

  <div id="login" class="col-md-6">
    <h2> Login </h2>
    <%= form_tag sessions_path do %>
        <div class="form-group">
          <%= label_tag :email_id %><br>
          <%= email_field_tag :email_id %>
        </div>
        <div class="form-group">
          <%= label_tag :password %><br>
          <%= password_field_tag :password %>
        </div>
        <%= submit_tag "Log In" %>
    <% end %>
  </div>

</div>